camel-tooling/camel-lsp-client-vscode

- Changelog.md
- src/extension.ts
to avoid conflict with Java Extension pack
by side effect, it is also fixing the Spring-boot dashboard whcih wasn't showing up.
and I don't know how to write the test :'(
> Use a specific command name to Apache Camel (#65)

- .travis.yml
by default on travis, dist has been upgraded from trusty to xenial, the
old way is not workign anymore
> Use service instead of before_install script for xfvb #102

- Changelog.md
- package.json
> Update to name approved by Red Hat legal department #119

- .gitignore
- .vscodeignore
- Changelog.md
- Readme.md
- package.json
- src/extension.ts
- src/test/catalog.version.test.ts
- src/test/runTest.ts
- testFixture/test-catalog-version.xml
Please note that the format send to the server side contains an extra
layer of "camel". It is to follow-up
conventions of xml and Java Language server implementations. It also
allows in the future to potentially read properties of other Languages.
requires https://github.com/camel-tooling/camel-language-server/pull/324
4. Approved PR
> FUSETOOLS2-56 - Allow to use specific Camel Catalog version

- Changelog.md
- src/JavaManager.ts
- src/extension.ts
- src/test/index.ts
- src/test/javamanager.test.ts
Language Server
it will allow users that don't have java available on system path to
rely on the java.home VS Code settings.
4. Approved PR
> FUSETOOLS2-433 - reuse VS Code settings for java.home to launch Camel

- scripts/postinstall.js
I think it would be nice to provide a release of VS Code Language support for Camel with a tagged version.
> FUSETOOLS2-561 - use tagged Camel language Server 1.1.0

- package.json
given that it provides support for Apache Camel Kafka Connectors. it
will allow to find the project on VS Code Marketplace when searching for
"kafka"
> FUSETOOLS2-614 - add Kafka in keywords

- .travis.yml
- Jenkinsfile
it allows to ensure that the package-lock.json is respected
> FUSETOOLS2-700 - use npm CI instead of npm install

- Jenkinsfile
it is no more needed for a while. it was removed from travis but not
from jenkins
see https://github.com/camel-tooling/camel-lsp-client-vscode/commit/b4ef8c367c06daba77c9ca9200706194b15257f4#diff-354f30a63fb0907d4ad57269548329e3
> Remove npm install --ignore-script call in jenkins job

- .travis.yml
- package-lock.json
- package.json
master is broken since release of VS Code 1.50.0.
To fix it, it requires to upgrade vscode-extension-tester to 3.2.1.
A manual upgrade of vscode-extension-tester-locator in package-lock.json is required as dependabot didn't want to pick it for unknown reasons.
This new version of vscode-extension-tester requires a newer version of fs-extra 9.0.1.
The fs-extra 9+ requires a newer version of node (10+) so need to update the Travis configuration (updated to lts/*, so currently 12).
Last built not least, the cache of Travis needed to be cleared.
> Fusetools2 782 fix broken master and several pr

- Jenkinsfile
VS Code Java requires java 11 for some time now but last release now
enforces it for more actions which is causin gour tests to break
> Upgrade to JDK 11 for jenkins requirements

- Changelog.md
requires https://github.com/camel-tooling/camel-language-server/pull/543
> FUSETOOLS2-928 - upgrade default Camel version to 3.7.0

- src/extension.ts
(`show(preserveFocus?: boolean): void`)
> 'show' is deprecated. Use the overload with just one parameter

- src/ui-test/xml_completion_support_test.ts
based on this log with added traces from this other [PR](https://github.com/camel-tooling/camel-lsp-client-vscode/pull/662):
```
✓ Duplicate endpoint options are filtered out (18021ms)
clicked on File > Revert File . Time since beginning of _clean method: 2809
Editor is no more dirty . Time since beginning of _clean method: 2869
clicked on File > Close Editor . Time since beginning of _clean method: 5452
Diagnostics for Camel URIs
✓ LSP diagnostics support for XML DSL (17775ms)
clicked on File > Revert File . Time since beginning of _clean method: 3231
Editor is no more dirty . Time since beginning of _clean method: 3292
2) "after all" hook: _clean for "LSP diagnostics support for XML DSL"
Auto-completion for referenced components IDs
clicked on File > Close Editor . Time since beginning …
```
> FUSETOOLS2-1190 - increase timeout to stabilize test

- src/ui-test/lsp_extension_test.ts
- src/ui-test/xml_completion_support_test.ts
```
/**
* Asserts non-strict equality (==) of actual and expected.
*
* @type T   Type of the objects.
* @param actual   Actual value.
* @param expected   Potential expected value.
* @param message   Message to display on error.
*/
equal<T>(actual: T, expected: T, message?: string): void;
```
> FUSETOOLS2-1192 - fix expected/actual in test assertion

- USAGE_DATA.md
- package-lock.json
- package.json
- src/extension.ts
based on https://github.com/camel-tooling/camel-lsp-client-vscode/pull/689
requires https://github.com/camel-tooling/camel-language-server/pull/637
report example in test instance https://app.woopra.com/project/test.vscode/analyze/report/trends/c0afwq5qlb
no tests provided. Cannot find a relevant way to test it as spies in
test are initialized after the activation of the VS Code extension.
> Fusetools2 1188 server initialization startup

- .github/workflows/windows-test.yml
cache usage can be noticed on this line https://github.com/camel-tooling/camel-lsp-client-vscode/runs/3142269896?check_suite_focus=true#step:4:16 on a rerun build.
it seems to be slightly faster: 5'31" compared to other comparable ones (a master build without modificatiosn to package-lock.json) which are between 5'45" and 5'52"
The main advantage is that it is a lot more readable
> FUSETOOLS2-1198 - use built-in caching mechanism for npm

- Changelog.md
- Readme.md
1.8 to launch Camel Language Server
> FUSETOOLS2-1229 - deprecation message in changelog and readme for java

- Changelog.md
- src/extension.ts
- src/ui-test/lsp_extension_test.ts
- use specific naming to improve readability in right-click status bar
- shortened status bar text
- provided tooltip
- use icon for running/OK/KO in status bar state for Camel Language
Server
- reactivate status bar UI test by using conditional to avoid flakiness
(which was the reason of deactivation)
> FUSETOOLS2-1158 - improve status bar

- Changelog.md
- package-lock.json
- package.json
keeping to 0.0.36 scheme for now. Will upgrade to 0.1.0 when the Camel Languaeg Server used will effectively requires Java 11
> Prepare next development iteration 0.0.36

- Changelog.md
- Readme.md
- package-lock.json
- package.json
- scripts/postinstall.js
It requires Java 11 thus increasing the version number
If Java 8 is configured locally, there are these errors available:
provided a wiki page to troubleshoot this issue https://github.com/camel-tooling/camel-lsp-client-vscode/wiki/Troubleshooting
It might be enough to guide users. At least as a first iteration. Another iteration could provide a notification mentioning that Java 11 is required like Tools for Microprofile is doing.
> FUSETOOLS2-1229 - upgrade Camel Language Server to 1.3.0-SNAPSHOT

- .github/workflows/vscode-versions-matrix.yml
- src/test/runTest.ts
Launch VS Code tests with several VS Code versions
- using Github Action as ti is a lot simpler than Circle CI
- launching with first compatible version declared and latest known
The idea is to potentially test older versions so that it has compatible APIs with Theia/Che/CodeReady Workspaces.  it doesn't solve the problem of potential CVEs.
> Launch VS Code tests with several VS Code versions

- Changelog.md
requires https://github.com/camel-tooling/camel-language-server/pull/663
> Changelog - default Camel Catalog upgrade to 3.11.2

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/vscode-versions-matrix.yml
- .github/workflows/windows-test.yml
- Readme.md
Requires the default branch migrated from `master` to `main` in GitHub Web UI before merging.
to synchronize with https://gitlab.cee.redhat.com/codeready-studio/cci-config/-/merge_requests/450
> FUSETOOLS2-1297 - migrate default branch name from master to main

- Jenkinsfile
the default branch for Jenkins git plugin is master
> FUSETOOLS2-1297 - fix jenkins file to use main branch

- .circleci/config.yml
- lt had been upgraded automatically to 16.x. it is causing trouble with global
dependencies and opencv doesn't contain prebuilt versions
- FUSETOOLS2-1359 - avoid use of sudo to install global npm dependencies on Circle C. It was previously required, now it is causing build failures. see https://stackoverflow.com/questions/50915469/simple-circleci-2-0-configuration-fails-for-global-npm-package-installation
for workaround
> FUSETOOLS2-1359 - use node 14.18 on CircleCI

- package.json
- tslint.json
requires https://github.com/camel-tooling/camel-lsp-client-vscode/pull/798
- use specific ts-lint configuration. Avoid checking inside the UI tests
resource folders which has node_modules that we do not want to be
analyzed
- ensure ts-lint is called on compilation
the goal is to avoid missing implicit dependencies which are leaking
from devDependencies and so missing at runtime with a built vsix (and
not detected by tests execution)
> FUSETOOLS2-1338 - detect missing dependencies at build time

- Changelog.md
compatibility with Eclipse Theia (and so Eclipse Che and CodeReady
Workspaces)
> Changelog: Downgrade fs-extra from 10.0.0 to 9.1.0 to ensure

- package-lock.json
- package.json
possible since upgrade of vscode-uitests-tooling to 2.2.1
it will allow compatibility with node 16 and simplify maintenance
> FUSETOOLS2-1394 - remove deprecated vscode-extension-tester-native

- package-lock.json
- package.json
Reverts camel-tooling/camel-lsp-client-vscode#980
to upgrade again: https://issues.redhat.com/browse/FUSETOOLS2-1648
> Revert "Bump mocha from 9.2.2 to 10.0.0"

- Changelog.md
- Readme.md
Only the classic catalog is covered. It allows to cover the Camel
Quarkus use case. It will cover the SpringBoot based use case when it
will be productized.
requires https://github.com/camel-tooling/camel-language-server/pull/784
> FUSETOOLS2-1677 - improve support for productized catalog

- Changelog.md
requires https://github.com/camel-tooling/camel-language-server/pull/816
> Changelog upgrade Camel default catalog from 3.18.0 to 3.18.1

- Changelog.md
see https://github.com/camel-tooling/camel-language-server/blob/62bbfc0fbc793421cab2e41d8c5da2546f2f98dd/pom.xml#L53 , the version 3.18.2 is already used
> Fix changelog for Camel Server 3.18.2

- src/ui-test/tests/lsp_extension.test.ts
it helps to stabilize Extensions UI tests. Now for some of the previous flaky tests, there is only a log provided and test is waiting a bit more and retrying.
https://github.com/camel-tooling/camel-lsp-client-vscode/actions/runs/5004091638/jobs/9046385267#step:14:80
```
Extensions view
TimeoutError: Wait timed out after 10113ms
at /home/runner/work/camel-lsp-client-vscode/camel-lsp-client-vscode/node_modules/selenium-webdriver/lib/webdriver.js:929:17
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
remoteStacktrace: ''
}
```
Oart of the various run, there were soem failures but none were related to the Extensions test.
> Stabilize UI test for Extensions

- .gitignore
- .vscodeignore
- tsconfig.json
We are defining custom extensions dir path here - https://github.com/camel-tooling/camel-lsp-client-vscode/blob/main/src/ui-test/uitest_runner.ts#L26 so we need to ignore/exclude that in right places
4. Approved PR
> Ignore .test-extensions folder used as extensions install path for UI tests

- Changelog.md
- package.json
requires https://github.com/camel-tooling/camel-dap-client-vscode/pull/427
> Update default version of Camel to 3.20.6

- src/test/suite/catalog.additional.component.test.ts
- src/test/suite/catalog.runtimeprovider.test.ts
- src/test/suite/catalog.version.test.ts
https://github.com/apupier/camel-lsp-client-vscode/pull/new/ImproveRobustnessOfTestsAfterCamel3.21Upgrade- tests were failing only on Ubuntu on CI
- added conditional wait, they are not perfect for sure but allows tests to currently pass
> Improve robustness of tests after Camel 3.21.0 upgrade

- package-lock.json
- package.json
Brings latest `vscode-extension-tester` v5.9.0 with support for `VS Code 1.81.0`
4. Approved PR
> Bump vscode-uitests-tooling from 4.0.3 to 4.0.5

- .github/workflows/main.yaml
- this is a first iteration generating information only for the node modules, it is missing the embedded jar
- for future, will need to generate it on jenkins too and maybe upload on GitHub tag or other places
> FUSETOOLS2-2193 - Generate SBOM during GitHub workflow

- .github/workflows/insider.yaml
- .github/workflows/main.yaml
Same as https://github.com/camel-tooling/camel-dap-client-vscode/pull/520
[1] [FUSETOOLS2-2242](https://issues.redhat.com/browse/FUSETOOLS2-2242)
LSP example with failed and cancelled jobs: https://github.com/camel-tooling/camel-lsp-client-vscode/actions/runs/6625828387
> FUSETOOLS2-2242: Collect ui-tests screenshoots and logs when cancelled

- .github/workflows/main.yaml
The language server is added as a child of another top level component instead of the VS Code extension itself but not found another way to do it in SBOM. it is not the nicest but it improves a lot the analysis anyway.
> FUSETOOLS2-2206 - Include Language Server in Model hierarchy of SBom

- Changelog.md
- Readme.md
- package.json
- src/extension.ts
- src/requirements/requirements.ts
- src/requirements/settings.ts
it was previously relying on `java.home` from VS Code Java, which has been deprecated and now removed
> FUSETOOLS2-2269 - Provide a setting for jdk to use to launch the Language Server

- .github/workflows/camel_version.yaml
- src/ui-test/tests/camel.settings.test.ts
- src/ui-test/tests/env/check.camel.version.ts
- src/ui-test/tests/env/set.camel.version.ts
- src/ui-test/tests/modelines.test.ts
- src/ui-test/tests/properties.test.ts
- src/ui-test/uitest_runner.ts
- src/ui-test/utils/testUtils.ts
> FUSETOOLS2-2201: Testing with productized versions of Camel

- Changelog.md
requires https://github.com/camel-tooling/camel-language-server/pull/1061
> Update Camel Quarkus Catalog from 3.6.0 to 3.7.0

- Jenkinsfile
Draft for generating sbom for vscode extensions on jenkins.
Some open questions are:
- Should we install jq and cyclonedx?
- Should we archive/upload the generate sbom?
> FUSETOOLS2-2207: Generate sbom for vscode extensions on jenkins

- .vscode/launch.json
the extensionTestsPath must point to the index file as it is done in the runTests class
for reference
https://code.visualstudio.com/api/working-with-extensions/testing-extension#advanced-setup-your-own-runner
Note: will surely need to report similar change in all of our extensions
> FUSETOOLS2-2308 - Fix launch configuration

- Changelog.md
- package-lock.json
- package.json
'expand-home-dir'` error
the `expand-home-dir` was defined as `devDependencies` on top of `dependencies`. it must be defined only in `dependencies`
> Fix regression of extension not activating with `Cannot find module

- src/commands/AbstractCamelCommand.ts
- src/commands/AbstractNewCamelRouteCommand.ts
- src/commands/NewCamelKameletCommand.ts
- src/commands/NewCamelPipeCommand.ts
- src/commands/NewCamelRouteCommand.ts
- src/commands/NewCamelRouteFromOpenAPICommand.ts
- src/commands/TransformCamelRouteCommand.ts
- src/ui-test/tests/commands.transform.test.ts
The "tranform route to YAML" command was accepting any filename as output. This was fixed by using the same logic in the "create new route" commands.
> FUSETOOLS2-2411: Fix transform route command filename validation

- Changelog.md
- package.json
- src/commands/NewCamelRouteFromOpenAPICommand.ts
- src/requirements/CamelJBang.ts
- src/tasks/CamelAddPluginJBangTask.ts
- src/ui-test/resources/camel_route_command/Java.java
- src/ui-test/resources/camel_route_command/XML.xml
- src/ui-test/resources/camel_route_command/YAML.yaml
- src/ui-test/resources/camel_transform_command/YAML.yaml
- The generated routes have slightly changed
- Camel route generation from OpenAPi spec has been moved to a specific
camel jbang plugin
https://camel.apache.org/manual/camel-4x-upgrade-guide-4_7.html#_camel_jbang
> Update default Camel JBang version to 4.7.0

- src/commands/NewCamelKameletCommand.ts
- src/commands/NewCamelQuarkusProjectCommand.ts
- src/commands/NewCamelRouteCommand.ts
- src/commands/NewCamelRouteFromOpenAPICommand.ts
- src/commands/NewCamelSpringBootProjectCommand.ts
as recommended by Sonarlint
https://sonarcloud.io/organizations/camel-tooling/rules?open=typescript%3AS1444&rule_key=typescript%3AS1444
4. Approved PR
> Use readonly for public static property

- resources/spring-boot/tasks.json
SpringBoot 4.8
to have suspend debugger on start working
> FUSETOOLS2-2463 - provide comment for requirements on Camel on

- Changelog.md
- package.json
- src/commands/TransformCamelRouteCommand.ts
- src/commands/TransformCamelRoutesInFolderCommand.ts
- src/extension.ts
- src/ui-test/tests/commands.transform.test.ts
- src/ui-test/utils/testUtils.ts
- Add tranform commands to the "New Camel file" contextual menu
- Right clicking a file provides de ability to transform it to XML/Yaml DSLs
- Right clicking a folder tries to transform all routes in it to XML/Yaml DSLs
> FUSETOOLS2-2458 - Provide contextual menu to transform routes

- Changelog.md
- package.json
- src/commands/NewCamelProjectCommand.ts
- src/requirements/CamelJBang.ts
- src/requirements/utils.ts
- src/tasks/CamelExportJBangTask.ts
- src/ui-test/tests/commands.projects.test.ts
- Removes "enablement" for the project creation commands because we will be always choosing a folder work with.
- Project creation commands do not depend on the workspace root anymore and can be used without one.
- Refactor existing tests to use the additional folder selection dialog.
- Opens a new VSCode instance in the newly created project's folder.
> FUSETOOLS2-2113 - Allows selection of folder when creating projects

- Changelog.md
- src/extension.ts
every two minutes, there are events didOpen and didClose for package.json files (not found the reason).
It is polluting Camel logs. Potentially leading to killing the server. Given that the Camel Language server does not provide anything for package.json files, the workaround consists in providing a more strict document selector to discard package.json. As json file, we provide completion only in VS Code launch.json and tasks.json files.
> FUSETOOLS2-2508 - Do not register the Camel Language Server for package.json file

- Changelog.md
- package.json
- src/commands/AbstractNewCamelProjectCommand.ts
- src/commands/NewCamelProjectCommand.ts
- src/commands/NewCamelQuarkusProjectCommand.ts
- src/commands/NewCamelSpringBootProjectCommand.ts
- src/extension.ts
- src/test/suite/camel.project.command.test.ts
Adds Create Camel projecy to the welcome screen
- Rename NewCamelProjectCommand class to reflect its abstract nature.
- Create a 'generic' NewCamelProjectCommand that asks the user to select a runtime. Register the command with 'enablement = false' so that its does not show in the command palette.
- Refactor other classes with the new project structure.
> Adds Create Camel project to the welcome screen

- docs/index.md
productized versionf
and reported https://issues.redhat.com/browse/FUSETOOLS2-2533 to add the same for Spring Boot
> Provide documentation to export to Camel Quarkus project with

- .vscode/launch.json
- src/ui-test/uitest_runner.ts
- tsconfig.json
- Adds launch configuration to start ui-tests.
- Adds launch configuration to attach to a running node process
(usefull when launching from the terminal with VSCode's auto attach
feature enabled).
- Adds better handling of exceptions in the ui-test runner. The
runner will print the exception message and stack trace to the
console.
> chore: add launch configurations to debug ui-tests

- .github/workflows/camel_version.yaml
- .github/workflows/insider.yaml
- .github/workflows/main.yaml
workaround as some tests started to fail on CI
reported https://issues.redhat.com/browse/FUSETOOLS2-2538 to switch it back to latest
it allows to unblock work on the other PRs
> Use MacOS 13 on GitHub CI

- src/test/suite/camel.openapi.command.test.ts
- src/ui-test/tests/01_commands.projects.welcome.content.button.test.ts
- src/ui-test/tests/09_commands.openapi.test.ts
- src/ui-test/tests/11_commands.transform.test.ts
- src/ui-test/tests/14_properties.test.ts
- src/ui-test/utils/testUtils.ts
on GitHUb Actions with MacOS 13, it often requires more time. I noticed that for some of them it is also failing (less often) on Windows
> Stabilize tests on CI

- Changelog.md
requires https://github.com/camel-tooling/camel-language-server/pull/1249
> changelog: Update default Camel Catalog version from 4.10.0 to 4.10.2

- src/ui-test/tests/14_properties.test.ts
it was resulting to next test to not be able to activate the extension. this test doesn't need to save the file when closing the editor as the file is deleted right after. Note that I have not found why when trying to save there was an error stating that the file does not exist.
> FUSETOOLS2-2540 - avoid flakiness in tests due to file cannot be saved

- Changelog.md
- src/commands/AbstractNewCamelProjectCommand.ts
- src/test/suite/camel.project.command.test.ts
Quarkus or Spring Boot project
based on https://github.com/KaotoIO/vscode-kaoto/pull/826/files
> FUSETOOLS2-2554 - Allow hyphen in Artifact Ids when exporting to a Camel

- src/test/suite/camel.kamelet.command.test.ts
in test
on Windows on Ci, it regularly failed with timeout of 5 seconds. Fo rinstance, on another windows run, it pwas succesful  but the whole test took 4s https://github.com/camel-tooling/camel-lsp-client-vscode/actions/runs/13964203526/job/39090907722?pr=2140#step:14:96
> FUSETOOLS2-2566 - increase timeout to create kamelet file in subfolders

- src/ui-test/uitest_runner.ts
I have noticed that the all UI tests are executed all the time even if I call only one specific file to be run
4. Approved PR
> fix: prevent uitest_runner.js to be executed either when only some specific test is called

- Changelog.md
doesn't have an alias for API-based component
requires https://github.com/camel-tooling/camel-language-server/pull/1309
> changelog Fix: provide completion for api properties on method which

- .github/workflows/insider.yaml
- .github/workflows/main.yaml
using the x86_64 (intel) architecture as with the arm based some tests to create project are always failing (but they are known to be flaky currently, just so far failed 100% time with arm). x86_64 GitHub macos runners are planned to be retired in 2027
fixes #2303
> Use MacOS 15 on CI
