camel-tooling/camel-lsp-client-vscode

scripts/preinstall.js

as the github organization has been renamed

#5 - fix download URL

---

Readme.md

#6 - Fix indentation in readme

---

.travis.yml
sonar-project.properties

#19 - Activate Sonar analysis

---

src/extension.ts

#19 - remove extra semicolon

---

package.json
scripts/preinstall.js

fixes #7 
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

download server from central/sonatype (#7)

---

.travis.yml

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

auto increment patch version so deploy always works (#21)

---

package.json

Use official category "Programming Languages"

---

src/test/completion.test.ts
testFixture/apacheCamel.java

Provide basic test for java completion (#35)

---

src/extension.ts

Remove unused code

---

sonar-project.properties

Fix configuration of Sonar for tests (#15)

---

package-lock.json
package.json

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

bumping version to 0.0.7

---

Contributing.md

Provide step by step draft for providing a new version on Marketplace

---

package-lock.json
package.json

to be ready for next iteration

Bump version to 0.0.8

---

scripts/preinstall.js

Use 1.1.0-SNAPSHOT version of Server

---

package-lock.json
package.json

Prepare next iteration 0.0.9

---

package-lock.json
package.json

I really dont get the benefit of this package-lock.json, just committing a lot of information that we don't use :(

Prepare for next iteration release 0.10.0

---

Changelog.md
Readme.md

Add information on new feature "find references of direct and direct-vm"

---

Changelog.md

based on https://github.com/camel-tooling/camel-lsp-client-vscode/pull/56

Update change log for hover

---

Changelog.md

Provide insert-and-replace changelog entry (#58)

---

Changelog.md
package-lock.json
package.json

Prepare next iteration release 0.11.0

---

Changelog.md
package-lock.json
package.json

Prepare next iteration release 0.12.0

---

Changelog.md

Provide changelog entry for completion for ids of direct/direct-vm/vm/seda

---

package-lock.json
package.json

Prepare for next iteration 0.0.13

---

src/extension.ts

Log error instead of silently ignoring it #73

---

Contributing.md

Provide information to start project in dev mode #74

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/175 to be merged before

Provide changelog for log file location

---

Changelog.md

Changelog Live validation ( camel-tooling/camel-language-server#116 )

---

Changelog.md

camel-tooling/camel-language-server#135

Changelog entry for "find reference" in all opened documents

---

Changelog.md

to be merged after https://github.com/camel-tooling/camel-language-server/pull/194

Include Camel 2.23.0 upgrade in changelog

---

Changelog.md
package-lock.json
package.json

Prepare next iteration release 0.14.0

---

package-lock.json
package.json

Upgrade vs code dependency to upgrade node.extend transitively #89

---

package-lock.json
package.json

it is fixing moderate security issue
https://nodesecurity.io/advisories/745

Upgrade TSLint to 5.12.1 #91

---

Changelog.md

camel-tooling/camel-language-server#210
requires https://github.com/camel-tooling/camel-language-server/pull/213 to be merged before

Changelog: Camel upgrade to 2.23.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/211 to be merged
EDIT: merged

Changelog: improved diagnostic camel-tooling/camel-language-server#204

---

package-lock.json
package.json

Upgrade vsce to fix moderate security vulnerabilities #98

---

Changelog.md

Changelog support syntax error camel-tooling/camel-language-server#225

---

Changelog.md

camel-tooling/camel-language-server#235
requires https://github.com/camel-tooling/camel-language-server/pull/237 to be merged before

Update changelog to indicate upgrade from Camel 2.23.1 to 2.24.0

---

package-lock.json
package.json

Upgrade indirect dependency to tar having vulnerability #104

---

Changelog.md
package-lock.json
package.json

Prepare next iteration 0.0.16

---

Changelog.md

camel-tooling/camel-language-server#240
requires https://github.com/camel-tooling/camel-language-server/pull/245

Update changelog for Camel upgrade to 2.24.1

---

Contributing.md
Jenkinsfile

to allow whole team to do a release

Add whole team to submitter list #107

---

Changelog.md
package-lock.json
package.json

Prepare next iteration 0.0.17

---

package-lock.json
package.json

https://github.com/camel-tooling/camel-lsp-client-vscode/pull/115 to be reviewed and merged first

Maintenance upgrade to latest dependencies

---

Changelog.md
package-lock.json
package.json

Prepare next iteration release 0.0.18

---

package.json
src/extension.ts

camel-tooling/camel-language-server#264
requires https://github.com/camel-tooling/camel-language-server/pull/265

Allow trigger of Camel completion on Spring Boot properties file type

---

.travis.yml

Exclude dependabot branches from non-PR jobs #130

---

.vscode/extensions.json

provide New Extension For TSLint And Remove Deprecated One

---

Changelog.md

Add in changelog the update from camel 2.24.1 to 2.24.2 of the server  #138

---

.travis.yml
Contributing.md
package.json

Modify 'scripts' to avoid having to call 'npm install --ignore-scripts'

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Provide GitHub templates for new issues and PRs #85

---

.gitignore
.travis.yml
.vscode/launch.json
.vscodeignore
package-lock.json
package.json
src/test/helper.ts
src/test/runTest.ts
src/ui-test/lsp_extension_test.ts
src/ui-test/resources/camel-context.xml
src/ui-test/resources/camel-route.xml
src/ui-test/xml_completion_support_test.ts
tsconfig.json
tslint.json

@apupier Hi, please have a look at least on package.json 'scripts' part, I did some modifications there. Thanks

Prepare automated tests for Camel LSP for VS Code

---

Changelog.md
package-lock.json
package.json

Prepare next iteration 0.0.19

---

package-lock.json
package.json
src/test/index.ts

see https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode
4. Approved PR

FUSETOOLS2-18 - Migrate to new recommended Test framework

---

package-lock.json
package.json
src/ui-test/lsp_extension_test.ts
src/ui-test/xml_completion_support_test.ts

Update 'vscode-extension-tester' to version 2.1.0 which fix failing UI tests

---

Changelog.md
package-lock.json
package.json

Prepare next development iteration 0.0.20

---

Changelog.md

FUSETOOLS2-66 add Quickfix for unknown properties in changelog

---

Changelog.md
Readme.md
package-lock.json
package.json
src/test/catalog.additional.component.test.ts
testFixture/test-additional-component.xml

requires https://github.com/camel-tooling/camel-language-server/pull/331
4. Approved PR

FUSETOOLS2-72 preference to provide additional components

---

package-lock.json
package.json
src/ui-test/lsp_extension_test.ts
src/ui-test/xml_completion_support_test.ts

Update tests to changes in vscode-uitests-tooling 2.0.0

---

Changelog.md

several parameters in XML DSL
requires https://github.com/camel-tooling/camel-language-server/pull/333
4. Approved PR

FUSETOOLS2-68 - Add improve range for Diagnostic range when tehre are

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/335
4. Approved PR

FUSETOOLS2-77 Camel 3 default catalog in Changelog

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/334
4. Approved PR

FUSETOOLS2-69 changelog for quickfix filtyered to similar ones

---

Changelog.md
package-lock.json
package.json

Prepare next iteration 0.0.21

---

Changelog.md

a Camel component property in properties file
requires https://github.com/camel-tooling/camel-language-server/pull/340
4. Approved PR

FUSETOOLS2-134 - add in changelog Completion for possible enum values of

---

Changelog.md

automatically added when auto-completing Camel component properties
requires https://github.com/camel-tooling/camel-language-server/pull/343
4. Approved PR

FUSETOOLS2-135 - In Properties file, the default values are

---

Changelog.md

requires https://github.com/camel-tooling/camel-lsp-client-vscode/pull/217 and https://github.com/camel-tooling/camel-language-server/pull/344
4. Approved PR

Fusetools2 136 chnagelog boolean completion

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/347
4. Approved PR

FUSETOOLS2-137 - changelog filtered completion list properties file

---

package-lock.json
src/ui-test/xml_completion_support_test.ts

Fix UI test issue for XML DSL Support

---

Changelog.md

file
requires https://github.com/camel-tooling/camel-language-server/pull/348
4. Approved PR

FUSETOOLS2-179 - changelog - insert-and-replace completion in Properties

---

Readme.md

requires https://github.com/camel-tooling/camel-language-server/pull/351/
4. Approved PR

FUSETOOLS2-178 - add information to provide productized Camel Catalog

---

Changelog.md
package-lock.json
package.json

Prepare next development iteration 0.0.22

---

Changelog.md
Jenkinsfile

requires https://github.com/camel-tooling/camel-lsp-client-vscode/pull/232
4. Approved PR

Fusetools 80 fix script

---

Changelog.md
package-lock.json
package.json
src/extension.ts
src/test/completion.properties.test.ts
src/test/runTest.ts
testFixture/application.properties

to keep support on application.properties file when Quarkus extension is
installed as it is defining a specific Language Mode
4. Approved PR

FUSETOOLS2-195 - Add quarkus language mode

---

Changelog.md
package-lock.json
package.json

Prepare next development iteration 0.0.23

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/364
4. Approved PR

FUSETOOLS2-191 - upgrade default Catalog from Camel 3.0.1 to 3.1.0

---

Changelog.md
package-lock.json
package.json

Prepare next iteration 0.0.24

---

Changelog.md

FUSETOOLS2-184 - add Diagnostic for properties file in changelog

---

package-lock.json
src/ui-test/lsp_extension_test.ts

FUSETOOLS2-301: Investigate and fix flaky UI test on 'Status bar'

---

Changelog.md

FUSETOOLS2-347 - Upgrade to Camel 3.2 (changelog)

---

src/ui-test/lsp_extension_test.ts

Temporary skip Status Bar UI tests to avoid repeating flaky build failures

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/389

FUSETOOLS2-466 - add Camel 3.3 default catalog in changelog

---

Changelog.md
package-lock.json
package.json

Prepare next iteration development 0.0.25

---

package.json
src/ui-test/xml_completion_support_test.ts

update version and fix API break
4. Approved PR

FUSETOOLS2-497 - upgrade to vscode-extension-tester 3.0.2

---

src/test/index.ts

it was mistakenly modified to play specific tests only.
4. Approved PR

Fix glob pattern to play all tests

---

Changelog.md
package-lock.json
package.json

Prepare next iteration 0.0.26

---

.editorconfig
src/test/completion.modeline.test.ts
test Fixture with speci@l chars/ModelineCompletion.java

FUSETOOLS2-470 - provide basic test for modeline completion

---

.editorconfig

Automatically add new line at end of files

---

Changelog.md

FUSETOOLS2-552 - add fix for regression in changelog

---

Changelog.md

groups
requires https://github.com/camel-tooling/camel-language-server/pull/416

FUSETOOLS2-548 - add in changelog rely on catalog for Camel properties

---

Changelog.md
Readme.md

properties of Camel property group
requires https://github.com/camel-tooling/camel-language-server/pull/417

FUSETOOLS2-549 - update readme and changelog about completion for

---

Changelog.md
src/ui-test/xml_completion_support_test.ts

requires https://github.com/camel-tooling/camel-language-server/pull/424

FUSETOOLS2-504 - add Upgrade to Camel 3.4.1 in changelog

---

src/ui-test/lsp_extension_test.ts

Signed-off-by: Marian Lorinc <mlorinc@redhat.com>
4. Approved PR

FUSETOOLS2-600 - Fix failing ui-tests after vscode 1.48.0 update

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/429 and https://github.com/camel-tooling/camel-lsp-client-vscode/pull/380

Camel 3.4.2 in changelog

---

Changelog.md

in changelog
requires https://github.com/camel-tooling/camel-language-server/pull/449

FUSETOOLS2-537 - completion for property-file in Camel K modeline added

---

Changelog.md
Readme.md

FUSETOOLS2-550 - mention dashed notation in readme and changelog

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/450

Add upgrade to Camel 3.5.0 by default in changelog

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/453

FUSETOOLS2-538 - completion for resource option in Camel K modeline

---

Changelog.md

Camel K modeline resource-like options
requires https://github.com/camel-tooling/camel-language-server/pull/461

FUSETOOLS2-707 - changelog entry for filtered out IDE config folder in

---

Changelog.md

FUSETOOLS2-774 - add completion for connector.class in changelog

---

Changelog.md
Readme.md

FUSETOOLS2-670 - Add Camel Kafka Support improvements in readme and

---

Changelog.md
Readme.md

requires https://github.com/camel-tooling/camel-language-server/pull/476

FUSETOOLS2-686 - add readme/changelog for completion on Converters

---

Changelog.md
Readme.md

FUSETOOLS2-789 - add changelog and readme for hover for camel.sink.* and

---

Changelog.md
Readme.md

requires https://github.com/camel-tooling/camel-language-server/pull/469

FUSETOOLS2-721 - add xml endpoint in outline feature in changelog and readme

---

Changelog.md

list of properties
requires https://github.com/camel-tooling/camel-language-server/pull/485

FUSETOOLS2-685 - add changelog for Refactor convert from Camel URI to

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/494 and https://github.com/camel-tooling/camel-lsp-client-vscode/pull/460

Fusetools2 831 changelog api hover

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/497

FUSETOOLS2-778 - changelog Camel K modeline split on several lines

---

Changelog.md

relates to https://github.com/camel-tooling/camel-language-server/pull/495

FUSETOOLS2-829 - changelog API name completion

---

Changelog.md

Modeline
requires https://github.com/camel-tooling/camel-language-server/pull/498

FUSETOOLS2-808 - changelog completion for jitpack dependency in Camel K

---

Changelog.md

relates to https://github.com/camel-tooling/camel-language-server/pull/496

FUSETOOLS2-830 - changelog api method name completion

---

Changelog.md

relates to https://github.com/camel-tooling/camel-language-server/pull/502

FUSETOOLS2-835 - changelog hover for Camel URl in Properties file

---

.circleci/config.yml

FUSETOOLS2-863 - provide CircleCi first iteration - build, test

---

.circleci/config.yml
sonar-project.properties

requires https://github.com/camel-tooling/camel-lsp-client-vscode/pull/478

FUSETOOLS2-863 - add Sonar to CircleCI configuration

---

src/test/catalog.additional.component.test.ts
src/test/catalog.version.test.ts
src/test/completion.util.ts

based on https://github.com/camel-tooling/camel-lsp-client-vscode/pull/480

FUSETOOLS2-833 - fix flaky test updated additional component is reflected in completion

---

.circleci/config.yml

it allows to validate that it all works together and it is easier to check that the flakiness it fixed or not
it is based on:
https://github.com/camel-tooling/camel-lsp-client-vscode/pull/478
https://github.com/camel-tooling/camel-lsp-client-vscode/pull/481
https://github.com/camel-tooling/camel-lsp-client-vscode/pull/480

Fusetools2 863 integrate UI test on Circle CI

---

src/ui-test/xml_completion_support_test.ts

https://sonarcloud.io/project/issues?id=camel-lsp-client-vscode&issues=AW8zCJb2eiXZ3z6dvKdu&open=AW8zCJb2eiXZ3z6dvKdu

Use primitive type

---

src/ui-test/xml_completion_support_test.ts

https://sonarcloud.io/project/issues?id=camel-lsp-client-vscode&issues=AXYI32aXgf0tQMvZ2cFE&open=AXYI32aXgf0tQMvZ2cFE
https://sonarcloud.io/project/issues?id=camel-lsp-client-vscode&issues=AXYI32aXgf0tQMvZ2cFF&open=AXYI32aXgf0tQMvZ2cFF

remove unused import

---

src/ui-test/lsp_extension_test.ts

expression
https://sonarcloud.io/project/issues?id=camel-lsp-client-vscode&issues=AXQK6WuTYa_Yl0_CdQ-B&open=AXQK6WuTYa_Yl0_CdQ-B

Remove unnecessary assertion since it does not change the type of the

---

Changelog.md
Readme.md

FUSETOOLS2-815 - add readme/changelog for diagnostic of soem Camel Kafka

---

Changelog.md
Readme.md

FUSETOOLS2-906 - add readme/changelog entry for diagnostic of mix of

---

Changelog.md
Readme.md

properties in Camel Kafka Connector

FUSETOOLS2-912 - changelog/readme for diagnostic of mix url and list of

---

Changelog.md
Readme.md

case or camel case
requires https://github.com/camel-tooling/camel-language-server/pull/540

FUSETOOLS2-909 - changelog for duplicated keys differentiated by dash

---

Changelog.md
Readme.md

Camel Kafka Connector Properties files

FUSETOOLS2-914 - changelog/readme for quickfix for unknown properties in

---

Changelog.md

FUSETOOLS2-848 - changelog for Camel kafka Connector Catalog upgrade to

---

Changelog.md
Readme.md

requires https://github.com/camel-tooling/camel-language-server/pull/546

FUSETOOLS2-849 - changelog/readme completion for basic configuration of

---

Changelog.md
Readme.md

requires https://github.com/camel-tooling/camel-language-server/pull/547

FUSETOOLS2-814 - description for connector.class value

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/551

changelog Camel Default Catalog 3.7.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/555

Changelog Camel Kafka Connector Catalog upgrade to 0.7.1

---

.vscodeignore

which are useless at run time. It helps to start reducing size.

FUSETOOLS2-965 - removing a bunch of files from vsix

---

Changelog.md
Readme.md
package.json
src/test/catalog.runtimeprovider.test.ts

requires https://github.com/camel-tooling/camel-language-server/pull/556

FUSETOOLS2-964 - Provide setting for runtime provider

---

package-lock.json
package.json
src/ui-test/xml_completion_support_test.ts

it is introducing direct dependencies although they are transitive only.
Would be better that the direct dependencies are fixing their own
dependency https://github.com/redhat-developer/vscode-extension-tester/issues/221#issuecomment-776503518

FUSETOOLS2-987 - compatibility with VS Code 1.53.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/558

Mention upgrade default Camel Catalog version to 3.7.2 in changelog

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/559

Changelog: Update default Camel Catalog version to 3.8.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/562

Changelog: provide Camel Quarkus Catalog 1.7.0

---

package-lock.json
package.json

vscode-uitests-tooling to fix master

FUSETOOLS2-1046 - upgrade vscode-extension-tester and

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/572

Changelog: update default Camel Catalog from 3.8.0 to 3.9.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/573

changelog: Update Default Camel Quarkus Catalog to 1.8.0

---

src/extension.ts

vscode.ExtensionContext.storagePath

Remove unused code using deprecated code

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/576

changelog: Update Camel Kafka Connector Catalog from 0.8.0 to 0.9.0

---

package.json

repsecting > respecting
4. Approved PR
1. [x] Tagged with relevant **PR labels**
2. [x] Green **job for PR**
4. [x] Green **master** branch build

Spelling fix in package.json, repsecting > respecting

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/580

changelog: Quarkus catalog upgrade from 1.8.0 to 1.8.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/582

FUSETOOLS2-1057 - changelog - Kafka topic completion

---

Changelog.md
package.json

not found a way to have a test able to launch a kafka Server within
typescript
demo video https://youtu.be/e4dkV8YhSoE
requires https://github.com/camel-tooling/camel-language-server/pull/585

FUSETOOLS2-1059 - Provide settings for Kafka Connection URL

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/590

FUSETOOLS2-1087 - changelog kamelet template id completion

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/595

FUSETOOLS2-1105 - changelog hover for kamelet template id

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/600

FUSETOOLS2-1106 - changelog kamelet property names completion

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/622

changelog camal kafka connector catalog update to 0.10.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/629

Changelog default Camel catalog from 3.10 to 3.11

---

Changelog.md

property=file: notation
requires https://github.com/camel-tooling/camel-language-server/pull/626

FUSETOOLS2-1183 - changelog for code action property-file to

---

Changelog.md

requires https://github.com/camel-tooling/camel-lsp-client-vscode/pull/657

Fusetools2 1180 completion for file

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/630

Changelog Quarkus 2.0

---

.vscode/tasks.json

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
4. Approved PR

automatic update to the tasks.json

---

Changelog.md

resource Camel K modeline option

FUSETOOLS2-1182 - changelog completion update related to API update of

---

package-lock.json
package.json
src/test/runTest.ts
src/ui-test/xml_completion_support_test.ts
test Fixture with speci@l chars/.vscode/settings.json

- disable trust store for unit test
- upgrade to latest vscode-extension tester to have ui test working

FUSETOOLS2-1204 - Adjust test to have them workign with VS Code 1.58+

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/636

Use Kamelet Catalog 0.3.0 instead of snapshot

---

.vscode/launch.json
Changelog.md
Readme.md
USAGE_DATA.md
package-lock.json
package.json
src/extension.ts

minimal telemetry to collect number of times the extension is activated
and see the OS shares to help driving priorities

FUSETOOLS2-1209 - provide opt-in telemetry

---

Changelog.md

based on https://github.com/camel-tooling/camel-lsp-client-vscode/pull/702
requires https://github.com/camel-tooling/camel-language-server/pull/645

Fusetools2 1231 changelog folding range route in java

---

.gitignore
package-lock.json
package.json
src/ui-test/lsp_extension_test.ts
src/ui-test/resources/vscode-settings.json
src/ui-test/xml_completion_support_test.ts

- stabilize ui tests
- activate disabled ui test status check
- use new functionality from vscode-uitests-tooling
Signed-off-by: Marian Lorinc <mlorinc@redhat.com>

FUSETOOLS2-966 - Stabilize LSP UI tests Jenkins pipeline

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/649

Changelog default camel catalog 3.11.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/652

Changelog: Update Camel Quarkus Catalog to 2.2.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/656

FUSETOOLS2-1232 - provide folding range for choice in Camel java routes

---

Changelog.md
USAGE_DATA.md
src/Telemetry.ts
src/extension.ts
src/test/telemetry.test.ts
test Fixture with speci@l chars/apacheCamel-telemetry.xml

requires https://github.com/camel-tooling/camel-language-server/pull/638
- mention in usage data
- add in changelog
- provide test
it will allow to have this kind of report https://app.woopra.com/project/test.vscode/analyze/report/trends/j6rpgiwdyn

FUSETOOLS2-1222 - telemetry for Opened Document

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/683

Changelog update Camel Quarkus Catalog to 2.4.0

---

src/requirements/findJavaRuntimes.ts
src/requirements/requirements.ts
src/requirements/settings.ts

The goal is then to enable tslint check on each build and be able to detect potential issues of dependencies

FUSETOOLS2-1338 - fix tslint violations related to quotes

---

Changelog.md
src/ui-test/xml_completion_support_test.ts

requires https://github.com/camel-tooling/camel-language-server/pull/687

Update default Camel Catalog version from 3.12.0 to 3.13.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/690

FUSETOOLS2-1378 - Update Camel K trait Catalog from 1.3.2 to 1.7.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/688

Update Kamelet Catalog from 0.4.0 to 0.5.0

---

Changelog.md
package.json

part of Azure/vscode-kubernetes-tools#985

Add keyword for discovery of extension when using Camel Yaml DSL

---

package-lock.json
package.json

fixes https://github.com/camel-tooling/camel-lsp-client-vscode/issues/836
4. Approved PR

fix: Downgrade fs-extra to have a check on native realpath function

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/695

Changelog: upgrade Camel Quarkus Catalog to 2.5.0

---

Changelog.md
package-lock.json
package.json

Prepare next development iteration 0.1.4

---

.github/workflows/vscode-versions-matrix.yml

Update VS Code version to 1.63.0 in tested matrix

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/699

Upgrade default camel catalog from 3.13 to 3.14

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/704

Changelog Camel Quarkus Catalog upgrade to 2.6

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/708

Changelog update kamelet Catalog to 0.6.0

---

Changelog.md

component that more completion is available with a local Kafka instance
requires https://github.com/camel-tooling/camel-language-server/pull/712

FUSETOOL2-1414 - Provide hint for `kafka`

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/720

Changelog upgrade Kamelete catalog to 0.7

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/722

Changelog update Camel catalog to 3.14.1

---

Contributing.md

extension release
for now only written in contributing guide awaiting for a better
automation

Add requirements of released version of Camel Language server for

---

.github/workflows/vscode-versions-matrix.yml
.github/workflows/windows-test.yml

see to check that we have logs and screenshots on failure https://github.com/camel-tooling/camel-lsp-client-vscode/actions/runs/1853148292

Store VS Code logs and UI Tests screenshots on Github CI Actions

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/738

Changelog upgrade Kamelet catalog to 0.7.1

---

Changelog.md
package-lock.json
package.json
scripts/postinstall.js

which is using Language server 1.5.0-SNAPSHOT

Prepare next development iteration 0.3.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/751

Changelog Camel Quarkus Catalog from 2.7.0 to 2.7.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/756

Changelog Camel Quarkus catalog upgrade to 2.8.0

---

package.json
src/ui-test/lsp_extension_test.ts

Update description of extension, i tis no more only for xml DSL (for a

---

Changelog.md

https://github.com/camel-tooling/camel-language-server/pull/761

Changelog update kamelet catalog from 0.7.1 to 0.8.0

---

Changelog.md
package-lock.json
package.json
scripts/postinstall.js

Prepare next development iteration 0.4.0 with upgraded language server

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/765

Changelog quarkus catalog 2.9.0 upgrade

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/766

Update Kamelet Catalog from 0.8.0 to 0.8.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/776

Changelog: upgrade Quarkus catalog to 2.10

---

Changelog.md

FUSETOOLS2-574 - Added CamelK Modeline insertion completion to changelog

---

Jenkinsfile

FUSETOOLS2-1681 - Changed joshiraez to jraez in Jenkins

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/781#event-6947221723

Update default Camel catalog to 3.18

---

scripts/postinstall.js

Bump LSP version to 1.6.0

---

Changelog.md
package-lock.json
package.json
scripts/postinstall.js

Prepare 0.5.0 snapshot

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/800

Changelog update Camel Quarkus catalog to 2.11.0

---

Changelog.md
package.json

4. Approved PR
Adds urls to the config settings to review available Camel Catalogs
Link to issue: https://issues.redhat.com/browse/FUSETOOLS2-1724

[FUSETOOLS2-1724] Provided urls to check available catalog versions

---

src/requirements/findJavaRuntimes.ts

Removed unused reject causing warnings

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/810

Changelog update Camel Quarkus catalog to 2.12.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/813

Changelog Kamelet catalog upgrade from 0.8.1 to 0.9.0

---

.circleci/config.yml
.github/workflows/vscode-versions-matrix.yml
.github/workflows/windows-test.yml
package-lock.json
package.json
src/ui-test/utils/testUtils.ts
src/ui-test/xml_completion_support_test.ts

Bump extester to 5.0.0 and uitests-tooling to 2.3.3

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/824

FUSETOOLS2 - 1815 - Support CRD Yaml

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/826

Changelog upgrade Camel Quarkus Catalog to 2.13.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/828

FUSETOOLS2-1817 - Changelog support plain Camel Yaml DSL

---

Changelog.md
package-lock.json
package.json
scripts/postinstall.js

requires https://github.com/camel-tooling/camel-language-server/pull/834

Prepare for next development iteration 0.6.0 with 1.8.0-SNAPSHOT server

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/836

Changelog Camel default runtime 3.19.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/839

Changelog Kamelet Catalog update to 0.9.0

---

src/test/completion.util.ts

to ease investigation on flaky tests

FUSETOOLS2-1860 - improve error message on test failure

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/851

Changelog upgrade Kamelet Catalog from 0.9.1 to 0.9.3

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/852

changelog: Update Camel Quarkus Catalog from 2.13.0 to 2.14.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/864

changelog: kamelet catalog upgrade from 0.9.0 to 0.10.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/866

changelog default Camel Catalog update to 3.20

---

Contributing.md

there is no job triggered when creating a tag

Fix contributing guide to release

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/874

Changelog Update default Camel Catalog version from 3.20.0 to 3.20.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/881

Changelog - Update Kameletet catalog from 0.10.0 to 3.20.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/887

Changelog upgrade Camel Quarkus catalog to 2.16.0

---

package-lock.json
package.json
src/ui-test/lsp_extension_test.ts

Fix UI tests to unblock main branch

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/907

Changelog: upgrade Kamelet catalog to 3.20.2

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/894

Changelog: catalog update to 3.20.2

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/actions/runs/4559440838

Changelog: catalog update to 3.20.3

---

Jenkinsfile

FUSETOOLS2-1930 - provide JBang on Jenkins

---

package-lock.json
package.json
scripts/postinstall.js

Prepare next development iteration 0.8.0 and upgrade server to

---

src/ui-test/resources/camel-context.java
src/ui-test/tests/java_completion_support.test.ts

FUSETOOLS2-32: Add UI Tests for Java DSL support in VS Code LSP client

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/919

changelog: update Kamelet catalog to 3.20.3

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/925

Changelog - update Camel Catalog to 3.20.4

---

docs/content/commands.md

Fix missing image at github pages documentation

---

Changelog.md
package.json
src/requirements/CamelJBang.ts
src/test/suite/camel.jbang.version.test.ts

FUSETOOLS2-2043: Provide settings in VS Code for Camel JBang version

---

.github/workflows/main.yaml
Changelog.md
package-lock.json
package.json

Bump extension engine to 1.76.0 tu support latest three vscode versions

---

src/test/runTest.ts

FUSETOOLS2-2093: Unit tests execution perform two downloads of vscode instance for testing

---

.github/workflows/main.yaml
src/ui-test/resources/vscode-settings.json
src/ui-test/tests/01_lsp_extension.test.ts
src/ui-test/tests/java_completion_support.test.ts
src/ui-test/tests/xml_completion_support.test.ts
src/ui-test/tests/yaml_completion_support.test.ts
src/ui-test/uitest_runner.ts
src/ui-test/utils/contentAssist.ts
src/ui-test/utils/testUtils.ts

Enable GH actions workflow UI tests execution on macOS and Windows

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/936

Changelog: update Camel default catalog to 3.20.5

---

src/ui-test/resources/camel_route_command/Java.java
src/ui-test/resources/camel_route_command/XML.xml
src/ui-test/resources/camel_route_command/YAML.yaml
src/ui-test/tests/camel_route_command.test.ts

FUSETOOLS2-1987: Add UI test for Camel Route DSL command execution

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/942

Changelog Kamelet Catalog upgrade to 3.20.5

---

package.json

note: I found no way to provide a placeholder (as suggested in issue raised)

FUSETOOLS2-1878 - improve description of Camel catalog version

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/947

FUSETOOLS2-2120 - changelog Provide Camel Quarkus debug profile in completion

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/951

Upgrade default Camel Catalog to 3.21.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/952

Upgrade default Kamelet Catalog to 3.20.6

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/955#event-9725689951

Changelog Kamelet Catalog 3.21.0

---

src/ui-test/tests/camel.settings.test.ts
src/ui-test/utils/testUtils.ts

FUSETOOLS2-143: Create UI Tests for providing of additional Camel components settings

---

src/ui-test/resources/code-navigation.xml
src/ui-test/resources/codeNavigation.java
src/ui-test/tests/code.navigation.test.ts
src/ui-test/utils/testUtils.ts

FUSETOOLS2-1990: Create UI Tests for code navigation to Camel Contexts and Routes

---

scripts/postinstall.js
src/extension.ts
src/requirements/JavaManager.ts
src/requirements/requirements.ts
src/ui-test/tests/camel.settings.test.ts

FUSETOOLS2-2157: Fix code smells reported by SonarCloud analysis

---

.eslintrc.json
src/extension.ts
src/requirements/settings.ts
src/test/runTest.ts
src/test/suite/completion.util.ts
src/ui-test/tests/camel.settings.test.ts
src/ui-test/uitest_runner.ts

Configure eslint to warn about floating promises

---

Jenkinsfile

tried the modified script with this maually replyaed and modified job: https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Fuse/job/VSCode/job/vscode-camel-lsp-release/1807/

FUSETOOLS2-2133 - use Java 17 on Jenkins to test

---

USAGE_DATA.md
src/extension.ts

FUSETOOLS2-2177 - provide basic telemetry for commands

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/971#event-10251784470

Changelog: update Camel Quarkus catalog to 3.2.0

---

Changelog.md

Adding FUSETOOLS2-1417 changelog message

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/973

FUSETOOLS2-2165 - changelog Camel K trait catalog upgrade

---

Changelog.md
package.json
src/extension.ts

file
requires https://github.com/camel-tooling/camel-language-server/pull/980

FUSETOOLS2-2182 - Provide completion for traits in VS Code tasks.json

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/985

Changelog upgrade quarkus to3.4.0

---

Changelog.md
package.json
src/extension.ts

requires https://github.com/camel-tooling/camel-language-server/pull/984

2189 support yml files

---

src/ui-test/tests/dsls.test.ts

FUSETOOLS2-2204: Fix wrong file names in DSL test

---

.github/workflows/main.yaml
.gitignore
scripts/postinstall.js

- Download sbom corresponding to embedded Camel Language Server
- Merge it with the one of the VS Code application
do it for now on GitHub Workflow, will surely need to do it on Jenkins too. keeping it as a seprate step.
requires https://github.com/camel-tooling/camel-language-server/pull/994

FUSETOOLS2-2197 - Include Camel LS Bom

---

src/ui-test/tests/modelines.test.ts

FUSETOOLS2-1992: Create UI Tests for Camel K modelines support

---

.github/workflows/insider.yaml
.github/workflows/main.yaml
Jenkinsfile
src/ui-test/tests/commands.test.ts

- Node 18.15 is the newest working with vscode-extension-tester
- it requires to not have ipv6 enabled on host

FUSETOOLS2-2018 - use Node 18

---

Changelog.md
package.json
src/ui-test/resources/camel_route_command/XML.xml

requires https://github.com/camel-tooling/camel-language-server/pull/996

Update default Camel Catalog and default JBang version to 4.1.0

---

Changelog.md
src/requirements/requirements.ts

forgot to upgrade the check providing more information from Java 11 to Java 17

Improve requirements for Java 17

---

Changelog.md

https://github.com/camel-tooling/camel-language-server/pull/995

Add autocompletion for config maps

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1004

Changelog: upgrade Camel Quarkus catalog to 3.5.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1013

Changelog Kamelet Catalog upgrade from 4.0.1 to 4.1.0

---

src/extension.ts
src/test/runTest.ts
src/test/suite/catalog.additional.component.test.ts
src/test/suite/catalog.runtimeprovider.test.ts
src/test/suite/catalog.version.test.ts
src/test/suite/completion.modeline.test.ts
src/test/suite/completion.properties.test.ts
src/test/suite/completion.test.ts
src/test/suite/completion.util.ts
src/test/suite/helper.ts
src/test/suite/index.ts
src/test/suite/telemetry.test.ts
src/ui-test/uitest_runner.ts
src/ui-test/utils/testUtils.ts

FUSETOOLS2-2252: Add missing headers for (ui-)test files

---

Changelog.md
package.json

requires https://github.com/camel-tooling/camel-language-server/pull/1020

Update default Camel to 4.2.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1022

Changelog: update Kamelet Catalog to 4.2.0

---

Changelog.md
resources/launch.json
resources/tasks.json
src/commands/NewCamelProjectCommand.ts
src/test/suite/camel.project.command.test.ts
src/ui-test/tests/commands.test.ts
src/ui-test/utils/testUtils.ts

FUSETOOLS-2250: Create .vscode with config files automatically after Camel Quarkus project is created

---

.github/workflows/insider.yaml
.github/workflows/main.yaml
Changelog.md
package-lock.json
package.json

FUSETOOLS2-2265: Bump extension vscode engine minimal version from 1.76.0 to 1.82.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1028

Changelog: update Camel Quarkus catalog from 3.5.0 to 3.6.0

---

.github/workflows/main.yaml

upload-artifact v4 is less permissive

Fix main branch - upload sbom a single time

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1035

Changelog default Camel catalog from 4.2.0 to 4.3.0

---

Changelog.md
package.json

Update default Camel JBang version from 4.2.0 to 4.3.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1038

Changelog update Kamelet Catalog from 4.2.0 to 4.3.0

---

Changelog.md
Readme.md
docs/index.md
package.json
src/commands/AbstractNewCamelRouteCommand.ts
src/commands/NewCamelKameletCommand.ts
src/extension.ts
src/test/suite/camel.kamelet.command.test.ts
src/test/suite/camel.route.command.test.ts
src/test/suite/helper.ts
src/ui-test/resources/kamelets/test-action.yaml
src/ui-test/resources/kamelets/test-sink.yaml
src/ui-test/resources/kamelets/test-source.yaml
src/ui-test/tests/commands.kamelet.test.ts
src/ui-test/utils/testUtils.ts

FUSETOOLS2-1933: Provide command to create a Kamelet with Yaml dsl

---

Changelog.md
scripts/postinstall.js

Use released Camel Language Server 1.17.0

---

Changelog.md
package-lock.json
package.json
scripts/postinstall.js

Prepare for next development iteration 0.16.0

---

Contributing.md
Readme.md

Minor improvements for Contributing.md and Readme.md

---

Changelog.md
package.json
src/commands/NewCamelFileCommand.ts
src/extension.ts
src/test/suite/camel.kamelet.command.test.ts
src/test/suite/camel.route.command.test.ts
src/ui-test/tests/commands.files.test.ts
src/ui-test/tests/commands.kamelet.test.ts
src/ui-test/tests/commands.openapi.test.ts
src/ui-test/utils/testUtils.ts

FUSETOOLS2-2274: Provide entry in File > New file... menu to create a Camel file

---

Changelog.md
scripts/postinstall.js

requires https://github.com/camel-tooling/camel-language-server/pull/1065

Use released 1.18.0 language server

---

Readme.md
docs/content/camel-uris.md
docs/content/commands.md
docs/index.md
package.json
src/test/suite/camel.route.command.test.ts
src/test/suite/completion.test.ts

Change labels using Yaml to YAML

---

Changelog.md
package.json

Update default Camel version used for Camel JBang from 4.3.0 to 4.4.0

---

.github/workflows/camel_version.yaml

build: Bump Red Hat productized Camel version from 4.0.0.redhat-00031 to 4.0.0.redhat-00036

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1072

Changelog - upgrade to Camel Quarkus 3.8.0 catalog

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1070

changelog - Update Kamelet Catalog from 4.3.0 to 4.4.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1078

changelog update default catalog to 4.4.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1082

changelog: update Camel Quarkus catalog to 3.8.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1084

changelog Update Camel Quarkus Catalog from 3.8.1 to 3.9.0

---

src/ui-test/tests/code.navigation.test.ts

Improve error message for test and fixing inverted expected/actual in

---

Changelog.md
package.json
src/ui-test/resources/camel-example-pipe.yaml

requires https://github.com/camel-tooling/camel-language-server/pull/1094

Update default Camel version to 4.5.0

---

package-lock.json
package.json
src/ui-test/tests/code.navigation.test.ts

- fix code.navigation.test
4. Approved PR

Bump vscode-uitests-tooling from 4.0.12 to 4.1.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1098

Changelog: update Kamelet catalog to 4.5.0

---

Changelog.md

and java to yaml
it was implemented with this commit https://github.com/camel-tooling/camel-lsp-client-vscode/commit/724b4c358da3eee3bc4ff051fdc3fb3f5142ba0a

FUSETOOLS2-2261 - add changelog entry for command to transform from xml

---

.github/workflows/main.yaml

Increase minimal VS Code version in main build from 1.82.3 to 1.86.2

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1105

Changelog - Update Camel Quarkus Catalog from 3.9.0 to 3.10.0

---

.github/workflows/coverage.yaml
.gitignore
.vscodeignore
package.json
src/ui-test/uitest_runner.ts

Setup code coverage for UI tests

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1109

Changelog: Update default Camel Catalog version from 4.5.0 to 4.6.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1111

Changelog Update Kamelet Catalog from 4.5.0 to 4.6.0

---

Changelog.md
scripts/postinstall.js

requires https://github.com/camel-tooling/camel-language-server/pull/1114 (and then sync on Maven Central)

Use released language server 1.21.0

---

.vscodeignore

the tests were passing but the built vsix wasn't starting

Reinclude node_modules in built vsix to fix main branch

---

Changelog.md

changelog: provide information for telemetry updates which triggered a

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1122

changelog: Update Camel Quarkus Catalog from 3.10.0 to 3.11.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1129

changelog: Camel Quarkus upgrade to 3.12.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1135

changelog: Update default Camel Catalog version from 4.6.0 to 4.7.0

---

.github/workflows/camel_version.yaml
.github/workflows/coverage.yaml
.github/workflows/insider.yaml
.github/workflows/main.yaml

build: Use Node 20 as default for github actions workflows

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1140

changelog: upgrade Camel Quarkus Catalog to 3.13

---

Changelog.md
scripts/postinstall.js

requires https://github.com/camel-tooling/camel-language-server/pull/1143 (and publish on Maven repository)

Use released Camel Language server 1.23.0

---

Jenkinsfile

example of Jenkins build (with manually modified Jenkinsfile on Jenkins instance job to tryout) https://studio-jenkins-csb-codeready.apps.ocp-c1.prod.psi.redhat.com/job/Fuse/job/VSCode/job/vscode-camel-lsp-release/2118/

Use node 20 on Jenkins

---

Changelog.md
package.json
src/commands/AbstractNewCamelRouteCommand.ts
src/commands/NewCamelFileCommand.ts
src/commands/NewCamelRouteCommand.ts
src/extension.ts
src/tasks/CamelInitJBangTask.ts
src/test/suite/camel.route.command.test.ts
test Fixture with speci@l chars/a sub folder/jbangInitRouteInSubFolder.camel.yaml

Explorer
for basic commands (create route with XXX DSL), it will create the file in the selected folder

FUSETOOLS2-2433 - provide contextual menu to create Camel file in

---

Changelog.md

Move entry in changelog to correct version

---

Changelog.md
src/commands/AbstractNewCamelRouteCommand.ts
src/commands/NewCamelKameletCommand.ts
src/commands/NewCamelRouteCommand.ts
src/extension.ts
src/test/suite/camel.kamelet.command.test.ts

FUSETOOLS2-2444 - use right-clicked folder to create kamelet

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1155

changelog: upgrade Camel Quarkus catalog to 3.14.0

---

Changelog.md
src/commands/NewCamelPipeCommand.ts
src/extension.ts
src/test/suite/camel.pipe.command.test.ts

FUSETOOLS2-2448 - use folder selected to create pipe with contextual

---

Changelog.md
src/commands/NewCamelRouteFromOpenAPICommand.ts
src/extension.ts
src/test/suite/camel.kamelet.command.test.ts
src/test/suite/camel.openapi.command.test.ts
test Fixture with speci@l chars/petstore.json

api with contextual menu "new file"

FUSETOOLS2-2450 - use folder selected to create camel route from open

---

package.json

based on https://github.com/camel-tooling/camel-lsp-client-vscode/pull/1900

FUSETOOLS2-2456: use sub menus for contextual menu

---

.github/workflows/main.yaml

ci: bump minimal tested VS Code version from 1.86.2 to 1.90.2

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1168

changelog: Update Kamelet Catalog from 4.7.0 to 4.8.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1169

Changelog: Update Camel Quarkus Catalog from 3.14.0 to 3.15.0

---

src/ui-test/tests/commands.transform.test.ts
src/ui-test/utils/testUtils.ts

- Remove .only method from test suite.
- Remove unused methods from testUtils.

Fix context menu transform test

---

Jenkinsfile

the version must be upgraded due to some other updates related to eslint upgrade; it was upgraded on GitHub Actions already
exception is:
```
10:02:40  + ./cyclonedx-linux-x64 merge --hierarchical --group com.github.camel-tooling --name vscode-apache-camel --version 1.6.0 --input-files node-sbom.json camel-ls-sbom.json --output-file manifest.json
10:02:40  Processing input file node-sbom.json
10:02:40      Contains 63 components
10:02:40  Processing input file camel-ls-sbom.json
10:02:40  Unhandled exception: System.ArgumentException: Unsupported specification version: 1.6
10:02:40     at CycloneDX.Models.Bom.set_SpecVersionString(String value)
10:02:40     at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& …
```

Fix sbom generation on Jenkins

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1186

changelog: upgrade default Camel catalog version to 4.8.1

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1189

changelog: update Camel Quarkus from 3.15.0 to 3.16.0

---

package-lock.json
package.json
src/ui-test/tests/01_lsp.extension.test.ts
src/ui-test/tests/camel.settings.test.ts
src/ui-test/tests/code.navigation.test.ts
src/ui-test/tests/commands.files.test.ts
src/ui-test/tests/commands.kamelet.test.ts
src/ui-test/tests/commands.openapi.test.ts
src/ui-test/tests/commands.pipe.test.ts
src/ui-test/tests/commands.projects.test.ts
src/ui-test/tests/commands.transform.test.ts
src/ui-test/tests/dsls.test.ts
src/ui-test/tests/modelines.test.ts
src/ui-test/tests/properties.test.ts
src/ui-test/uitest_runner.ts
src/ui-test/utils/contentAssist.ts
src/ui-test/utils/testUtils.ts

remove vscode-uitests-tooling dependency
4. Approved PR

chore(deps-dev): depend directly only on vscode-extension-tester package

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1196

changelog: Update Kamelet Catalog from 4.8.0 to 4.8.1

---

src/requirements/requirements.ts

note, when message is fine, to do same work in VS Code dap

Improve message to configure Java 17 for the Language Server

---

Changelog.md
scripts/postinstall.js

requires https://github.com/camel-tooling/camel-language-server/pull/1199
4. Approved PR

Use released Camel language server 1.27.0

---

Changelog.md
package-lock.json
package.json
scripts/postinstall.js

Prepare next development iteration 1.8.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1208

FUSETOOLS2-2508 - changelog for fix to language server shutdown overnight

---

Changelog.md

requires:
https://github.com/camel-tooling/camel-language-server/pull/1207
https://github.com/camel-tooling/camel-language-server/pull/1212
https://github.com/camel-tooling/camel-language-server/pull/1214

changelog: Camel catalogs update to 4.9.0

---

docs/content/other.md
docs/index.md

docs: add mention for automatic schema association for Camel yaml files

---

.github/workflows/camel_version.yaml

it corresponds to release number 4.4.4

Upgrade to latest 4.4 productized version used in test

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1227

FUSETOOLS2-2529 - changelog avoid potential NPE with FoldingRange

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1234

changelog: update Camel Quarkus catalog to 3.18.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1237

changelog: Update default Camel Catalog version from 4.9.0 to 4.10.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1239

Changelog - Update Kamelet Catalog from 4.9.0 to 4.10.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1246

changelog Update Camel Quarkus Catalog to 3.19.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1259

changelog: Update Camel Quarkus Catalog from 3.19.0 to 3.20.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1261

changelog: update default camel catalog version to 4.10.3

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1264

changelog: update default camel catalog version to 4.11.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1265

changelog: Update Camel kamelets Catalog from 4.10.2 to 4.11.0

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1272

changelog: Update Camel Quarkus Catalog from 3.20.0 to 3.22.0

---

scripts/postinstall.js

FUSETOOLS2-2584 - migrate from OSSRH to Central to retrieve embedded

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1282

changelog: update Camel Quarkus catalog to 3.23.0

---

Changelog.md
package.json
src/test/suite/catalog.runtimeprovider.test.ts
src/ui-test/tests/05_camel.settings.test.ts
test Fixture with speci@l chars/test-catalog-provider.xml

relates to camel-tooling/camel-lsp-server#1289
requires https://github.com/camel-tooling/camel-language-server/pull/1290

changelog: Remove support for Karaf as Runtime for the Catalog

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1291

changelog FUSETOOLS2-2585 - Support Camel XML IO namespace

---

Changelog.md
package.json

fix camel-tooling/camel-language-server#1288
requires https://github.com/camel-tooling/camel-language-server/pull/1294

Remove support for Kafka connected mode

---

docs/index.md

FUSETOOLS2-2533 - Add documentation to export to Spring Boot with

---

.github/workflows/add-issue-to-project.yml

Add new workflow - Add issue to GitHub Project

---

Changelog.md

requires https://github.com/camel-tooling/camel-language-server/pull/1326 https://github.com/camel-tooling/camel-language-server/pull/1325 https://github.com/camel-tooling/camel-language-server/pull/1320

Update Camel catalogs by default to 4.14

---

Changelog.md
package.json

requires https://github.com/camel-tooling/camel-language-server/pull/1347

Update default Camel to 4.14.1
